[package]
name = "shoes"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "A multi-protocol proxy server."
homepage = "https://github.com/cfal/shoes/"
repository = "https://github.com/cfal/shoes/"
readme = "README.md"
keywords = ["proxy", "proxy-server", "shadowsocks", "v2ray", "vmess"]
categories = ["command-line-utilities", "network-programming"]

[dependencies]
aes = "*"
argon2 = "*"
async-trait = "*"
aws-lc-rs = { version = "*", default-features = false }
base64 = "*"
blake3 = "*"
bytes = "*"
dashmap = "*"
digest = "*"
env_logger = "*"
futures = "*"
h3 = "*"
h3-quinn = "*"
http = "*"
log = { version = "*", features = ["release_max_level_info"] }
lru = "*"
md-5 = "*"
memchr = "*"
notify = "*"
parking_lot = "*"
percent-encoding = "*"
quinn = { version = "*", default-features = false, features = ["log", "platform-verifier", "runtime-tokio", "rustls-aws-lc-rs"] }
rand = "*"
rand_core = "*"
rcgen = { version = "*", features = ["x509-parser"] }
rustc-hash = "1"
rustls = "*"
serde = { version = "*", features = ["derive", "std"] }
subtle = "*"
serde_yaml = "*"
sha3 = "*"
socket2 = "*"
tokio = { version = "*", features = [
    "fs",
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "sync",
    "time",
] }
webpki-roots = { version = "*" }
x509-parser = "*"

[dev-dependencies]
tempfile = "*"
hyper = { version = "1", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["tokio", "server"] }
http-body-util = "0.1"
rustls-pemfile = "*"
rcgen = "*"
tokio-rustls = "*"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.6"

[profile.release]
opt-level = 3
lto = "fat"
strip = true
