[package]
name = "shoes"
version = "0.1.7"
edition = "2021"
license = "MIT"
description = "A multi-protocol proxy server."
homepage = "https://github.com/cfal/shoes/"
repository = "https://github.com/cfal/shoes/"
readme = "README.md"
keywords = ["proxy", "proxy-server", "shadowsocks", "v2ray", "vmess"]
categories = ["command-line-utilities", "network-programming"]

[dependencies]
aes = "0.8.4"
argon2 = "0.5.3"
async-trait = "0.1.88"
aws-lc-rs = { version = "1.13.1", default-features = false }
base64 = "0.22.1"
blake3 = "1.8.2"
bytes = "1.10.1"
cfb-mode = "0.8.2"
dashmap = "6.1.0"
digest = "0.10.7"
env_logger = "0.11.8"
futures = "0.3.31"
h3 = "0.0.8"
h3-quinn = "0.0.10"
hmac = "0.12.1"
http = "1.3.1"
log = "0.4.27"
md-5 = "0.10.6"
memchr = "2.7.4"
notify = "8.0.0"
parking_lot = "0.12.3"
percent-encoding = "2.3.1"
quinn = { version = "0.11.8", default-features = false, features = ["log", "platform-verifier", "runtime-tokio", "rustls-aws-lc-rs"] }
rand = "0.9.1"
rustc-hash = "1.1.0"
rustls = "0.23.27"
serde = { version = "1.0.219", features = ["derive", "std"] }
serde_yaml = "0.9.34"
sha3 = "0.10.8"
socket2 = "0.5.9"
tokio = { version = "1.45.0", features = [
    "fs",
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "sync",
    "time",
] }
tokio-rustls = { version = "0.26.2", default-features = false, features = ["logging", "tls12", "aws-lc-rs"] }
webpki-roots = { version = "1.0.0" }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.6"

[profile.release]
opt-level = 3
lto = "fat"
strip = true
